version: '3.8'

services:
  universalforumblock: 
    image: heavrnl/universalforumblock:1.0.0  
    ports:
      - "8006:8000"
    volumes:
      - ./user_configs:/app/user_configs
      - ./admin:/app/admin
    restart: unless-stopped
